(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(anzu-use-migemo t t)
 '(aw-keys '(106 107 108 105 111 104 121 117 112) t)
 '(beacon-color "#f1fa8c")
 '(flyspell-correct-interface 'flyspell-correct-completing-read t)
 '(highlight-indent-guides-auto-enabled t)
 '(highlight-indent-guides-method 'bitmap)
 '(highlight-indent-guides-responsive t)
 '(hydra-posframe-border-width 5)
 '(hydra-posframe-parameters '((left-fringe . 8) (right-fringe . 8)))
 '(imenu-list-auto-resize t t)
 '(imenu-list-entry-prefix "•" t)
 '(imenu-list-focus-after-activation t t)
 '(imenu-list-subtree-prefix "•" t)
 '(ispell-extra-args '("--sug-mode=ultra" "--lang=en_US" "--run-together") t)
 '(ispell-program-name "aspell" t)
 '(large-file-warning-threshold 1000000)
 '(markdown-fontify-code-blocks-natively t t)
 '(markdown-hide-markup nil t)
 '(markdown-hide-urls nil t)
 '(markdown-list-item-bullets '("★") t)
 '(migemo-coding-system 'utf-8)
 '(migemo-command "/opt/homebrew/bin/cmigemo")
 '(migemo-dictionary
   "/opt/homebrew/Cellar/cmigemo/HEAD-9a1cec4/share/migemo/utf-8/migemo-dict")
 '(migemo-options '("-q" "--nonewline" "--emacs"))
 '(migemo-regex-dictionary nil)
 '(migemo-user-dictionary nil)
 '(neo-autorefresh t t)
 '(neo-cwd-line-style 'button t)
 '(neo-mode-line-type nil t)
 '(neo-show-hidden-files t t)
 '(neo-theme 'nerd t)
 '(neo-window-fixed-size nil t)
 '(org-bullets-bullet-list '("" "" "" "" "" "" "" "" "" "") t)
 '(org-modern-block nil t)
 '(org-modern-checkbox '((88 . "") (45 . "") (32 . "")) t)
 '(org-modern-hide-stars nil t)
 '(org-modern-priority '((65 . "") (66 . "") (67 . "")) t)
 '(org-modern-progress nil t)
 '(org-modern-star ["" "" "" "" "" "" "" "" "" ""] t)
 '(org-modern-table-vertical 1 t)
 '(org-modern-timestamp t t)
 '(org-modern-todo nil t)
 '(org-todo-keyword-faces
   '(("WAIT" :foreground "#6272a4" :weight bold :width condensed)
     ("NEXT" :foreground "#f1fa8c" :weight bold :width condensed)))
 '(package-selected-packages '(el-get leaf))
 '(visual-fill-column-center-text t t)
 '(visual-fill-column-width 100 t)
 '(window-transparency 88 t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aw-leading-char-face ((t (:height 4.0 :foreground "#f1fa8c"))) nil "Customized with leaf in `ace-window' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(flyspell-duplicate ((t (:underline (:color "#50fa7b" :style wave)))) nil "Customized with leaf in `flyspell' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(flyspell-incorrect ((t (:underline (:color "#f1fa8c" :style wave)))) nil "Customized with leaf in `flyspell' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-face-amaranth ((t (:foreground "#f1fa8c"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-face-blue ((t (:foreground "#8be9fd"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-face-pink ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-face-red ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-face-teal ((t (:foreground "#61bfff"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(hydra-posframe-border-face ((t (:background "#323445"))) nil "Customized with leaf in `hydra-posframe' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(imenu-list-entry-face-1 ((t (:foreground "white"))) nil "Customized with leaf in `imenu-list' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(imenu-list-entry-subalist-face-0 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(imenu-list-entry-subalist-face-1 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(imenu-list-entry-subalist-face-2 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(imenu-list-entry-subalist-face-3 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-bold-face ((t (:foreground "#f8f8f2" :weight bold))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-gfm-checkbox-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-header-delimiter-face ((t (:foreground "#6272a4" :weight normal))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-header-face-1 ((t (:inherit outline-1 :weight bold :height 1.5))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-header-face-2 ((t (:inherit outline-1 :weight normal :height 1.2))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-header-face-3 ((t (:inherit outline-1 :weight normal :height 1.1))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-header-face-4 ((t (:inherit outline-1 :weight normal))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-italic-face ((t (:foreground "#f8f8f2" :slant italic))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-link-face ((t (:foreground "#f1fa8c"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-list-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-metadata-key-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-metadata-value-face ((t (:foreground "#8995ba"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-pre-face ((t (:foreground "#8be9fd"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(markdown-url-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-checkbox ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-date ((t (:foreground "#8995ba"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-document-title ((t (:foreground "#f8f8f2"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-done ((t (:background "#373844" :foreground "#216933" :strike-through nil :weight bold :width condensed))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-drawer ((t (:foreground "#44475a"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-footnote ((t (:foreground "#76e0f3"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-2 ((t (:inherit outline-2 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-3 ((t (:inherit outline-3 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-4 ((t (:inherit outline-4 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-5 ((t (:inherit outline-5 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-level-6 ((t (:inherit outline-6 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-link ((t (:foreground "#f1fa8c" :underline nil :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-list-dt ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-meta-line ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-date-active ((t (:background "#373844" :foreground "#f8f8f2" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-date-inactive ((t (:background "#373844" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-statistics ((t (:foreground "#6272a4" :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-tag ((t (:background "#44475a" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-time-active ((t (:background "#44475a" :foreground "#f8f8f2" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-modern-time-inactive ((t (:background "#44475a" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-priority ((t (:foreground "#ebe087"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-special-keyword ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-tag ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(org-todo ((t (:foreground "#51fa7b" :weight bold :width condensed))) nil "Customized with leaf in `org-theme' block at `/Users/shimadataketo/.doom.d/config_init.el'")
 '(vhl/default-face ((nil (:foreground "#FF3333" :background "#FFCDCD"))) nil "Customized with leaf in `volatile-highlights' block at `/Users/shimadataketo/.doom.d/config_init.el'"))
